name: Codecov
on:
  push:
    paths:
      - .github/workflows/test-frontend.yml
      - frontend/**
jobs:
  test-frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn
        working-directory: frontend
      - run: yarn test
        working-directory: frontend/packages/cat-reset
      - uses: codecov/codecov-action@v2
        with:
          verbose: true
          flags: frontend

    

