name: Codecov
on:
  push:
    paths:
      - .github/workflows/test-backend.yml
      - backend/**
jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "^1.17.0"
      - run: |
          go test -coverprofile=coverage.txt ./...
        working-directory: backend
      - uses: codecov/codecov-action@v2
        with:
          verbose: true
          flags: backend

